### ISSUE TITLE
ML intro

### ISSUE THREAD

**Issue by shivamgarg-ti** [trilogy-group/tu2k22-shivamgarg#28]
started the introduction

**Comment by shivamgarg-ti** [comment]
CSV OHLCV data set
<img width="884" alt="image" src="https://user-images.githubusercontent.com/110181688/185320235-04803e4e-634a-474f-b4d1-c15070f42479.png">

**Comment by shivamgarg-ti** [comment]
Commands used:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/110181688/185320633-13979352-dab8-42fc-8962-33dfc54fa429.png">

**Comment by kushal-ti** [comment]
:+1:
